Mvp/router header component
chingu-voyage4/Bears-Team-16 pull request #50
Opened 2018-03-06 07:20 UTC by aaayumi

https://waffle.io/chingu-voyage4/Bears-Team-16/cards/5a98600875b5a300257f8a6e

- React Router 
- Header component 

[in progress]
need to add tests

2018-03-06 11:40 UTC, thinktwice13 commented on client/src/components/Home.js
> +const fetchRecipes = gql`
Added graphql integration and a sample query. Will work when it is merged into `development`

2018-03-06 11:43 UTC, thinktwice13 requested changes
Having both `package-lock.json` and `yarn.lock` will cause some issues later in deployment. 
Aside from that, all good :+1:

2018-03-06 11:44 UTC, thinktwice13 submitted a review, later dismissed

2018-03-06 11:45 UTC, thomlom commented
So what should we keep ? `package-lock` or `yarn.lock` ?

2018-03-06 12:00 UTC, thinktwice13 commented
Correction: GraphQL will work once both this and `feature/api-methods-` are merged into development

@thomlom I don't like it, but I think `npm` is still more standard. But it won't be a problem for a while.

2018-03-07 06:58 UTC, aaayumi commented
So I removed `yarn.lock`.

2018-03-07 07:11 UTC, thomaslombart reviewed
Looks good to me!

2018-03-07 07:11 UTC, thomaslombart submitted a review, later dismissed

2018-03-07 09:30 UTC, thomaslombart approved these changes
Still looks good to me 🙂

2018-03-07 17:29 UTC, fredhawk approved these changes
Looks good to me. 👍

2018-03-07 19:08 UTC, merged