Components/fix header footer
chingu-voyage4/Bears-Team-16 pull request #99
Opened 2018-04-07 16:12 UTC by aaayumi

Header and footer components fix
- Header component's position is `fixed`
- Footer component's position is `relative`

2018-04-07 17:21 UTC, thinktwice13 reviewed
Footer is not at the bottom of the window, but hangs just below the content.

2018-04-10 07:07 UTC, thomaslombart submitted a review, later dismissed
Header is not responsive on mobile but looks good anyway!

2018-04-10 07:15 UTC, thinktwice13 requested changes
Footer still not working for me. It is now below the bottom of the window even on small amount of content

2018-04-10 18:46 UTC, thinktwice13 approved these changes

2018-04-10 18:47 UTC, merged